### ISSUE TITLE
JRuby 9000 compatibility (warning printed on start)

### ISSUE THREAD

**Issue by jhstatewide** [trinidad/trinidad#134]
After installing JRuby 9.0.3.0 and gem installing trinidad, the following error is printed to console during Trinidad start:

```
Deploying from /home/josh/hello_world as /
Initializing ProtocolHandler ["http-bio-0.0.0.0-3000"]
could not resolve compat version from '2.2.2' will use default
java.lang.IllegalArgumentException: No enum constant org.jruby.CompatVersion.RUBY2_2
	at java.lang.Enum.valueOf(Enum.java:236)
	at org.jruby.rack.DefaultRackConfig.getCompatVersion(DefaultRackConfig.java:87)
	at org.jruby.rack.DefaultRackApplicationFactory.initRuntimeConfig(DefaultRackApplicationFactory.java:306)
	at org.jruby.rack.DefaultRackApplicationFactory.createRuntimeConfig(DefaultRackApplicationFactory.java:252)
	at org.jruby.rack.DefaultRackApplicationFactory.init(DefaultRackApplicationFactory.java:87)
	at org.jruby.rack.RackApplicationFactoryDecorator.doInit(RackApplicationFactoryDecorator.java:112)
	at org.jruby.rack.PoolingRackApplicationFactory.doInit(PoolingRackApplicationFactory.java:111)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:100)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4994)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5492)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Although the error is displayed, a simple "hello world" Rack app seems to function normally.

**Comment by jhstatewide** [comment]
@kares: I looked into JRuby internals... it seems to list CompatVersions up to 2.1. 
If trinidad boots and it can't find the appropriate CompatVersion it says "using default". In that case, is trinidad set to 2.2 compat mode? And if so, do we need to log this exception? Despite the warning trinidad appears to function normally with a small test app + JRuby 9000. Another possibility would be forcing compat to 2.1 if it's undefined, although I don't know if that's the proper thing to do.

**Comment by kares** [comment]
as noted already, this should be fixed on master: https://github.com/trinidad/trinidad/commit/e6cd3418f9f38426f0fc1062e7e4983d0a35eeb5

**Comment by cshupp1** [comment]
This exact issue affected me on a new rails app generated from scratch today.
