### ISSUE TITLE
java.lang.IllegalArgumentException: Control character in cookie value or attribute

### ISSUE THREAD

**Issue by hydrogen18** [trinidad/trinidad#135]
I am using trinidad on JRuby 1.7.22 for a Ruby on Rails 4.1 app.

My application logs this many times per day

```
Error processing request
java.lang.IllegalArgumentException: Control character in cookie value or attribute.
	at org.apache.tomcat.util.http.CookieSupport.isV0Separator(CookieSupport.java:153)
	at org.apache.tomcat.util.http.Cookies.processCookieHeader(Cookies.java:340)
	at org.apache.tomcat.util.http.Cookies.processCookies(Cookies.java:168)
	at org.apache.tomcat.util.http.Cookies.getCookieCount(Cookies.java:106)
	at org.apache.catalina.connector.CoyoteAdapter.parseSessionCookiesId(CoyoteAdapter.java:997)
	at org.apache.catalina.connector.CoyoteAdapter.postParseRequest(CoyoteAdapter.java:751)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:403)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

It would be great if we did not get sent malformed cookies, but I don't think it is avoidable on the wild wild web.

The code paths in question are trying to do session extract for some sort of java session stuff. Since I am using Ruby On Rails, we do not ever set this java session stuff and do not need to check for it.

My conclusion was this can be changed by calling the java method `ServletContext.setSessionTrackingModes` and passing it the empty array. I could not find a reasonable way to do this, so I added a monkey patch like this to my `trinidad.rb`

```
  Trinidad::Lifecycle::WebApp::Default.class_eval do
    alias_method :original_configure, :configure
    def configure(context)
      original_configure(context)
      empty = Java::java.util.EnumSet.noneOf(Java::javax.servlet.SessionTrackingMode.java_class)
      context.getServletContext.setSessionTrackingModes(empty)
      context
    end
  end 
```

Do you have a suggestion for a better way to perform this configuration without a monkey patch?

**Comment by CloudPai** [comment]
hi，today I have the same problem and my solution is **clear cookies of the default webBrowser**.（I think the reason is when you debug  with the page such as http://localhost:8080 ,your value of cookies  are saved as no  standard form such as Chinese characters accidentally）
